[package]
name = "mos"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.29.0"
ropey = "1.6.1"
toml = "0.9.8"
serde = { version = "1.0.228", features = ["derive"] }
config = "0.15.19"
dirs = "6.0.0"
